HDF5
BlueQuartzSoftware/MetaForge pull request #48
Opened 2022-06-25 18:29 UTC by cryos

2022-07-20 14:54 UTC, joeykleingers requested changes

2022-07-20 14:54 UTC, joeykleingers commented on parsers/h5_parser.py
> +    return False
```suggestion
    return extension in self.ext_list
```

2022-07-20 15:59 UTC, joeykleingers requested changes

2022-07-20 15:59 UTC, joeykleingers commented on parsers/h5_parser.py
> +  def type_dispatch(self, value: any) -> str|None:
```suggestion
  def type_dispatch(self, value: any) -> str:
```

2022-07-20 15:59 UTC, joeykleingers commented on parsers/h5_parser.py
> +  def unpack_array(self, value: h5py.Dataset) -> str|None:
```suggestion
  def unpack_array(self, value: h5py.Dataset) -> str:
```

2022-07-20 16:00 UTC, joeykleingers commented on parsers/h5_parser.py
> +  def type_dispatch(self, value: any) -> str|None:
This pipe character in the return value errors out on my machine.

2022-07-20 16:02 UTC, joeykleingers commented on parsers/h5_parser.py
> +  def unpack_array(self, value: h5py.Dataset) -> str|None:
This pipe character in the return value errors out on my machine.

2022-07-21 12:14 UTC, cryos commented
@joeykleingers seemed reasonable, local testing everything looks OK. I think this is ready to merge

2022-07-21 12:16 UTC, joeykleingers approved these changes

2022-07-21 13:33 UTC, merged